---
title: "Milestone 4"
author: "Saul Soto"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(spotifyr)
library(lubridate)
library(readxl)
library(janitor)
library(rvest)
library(infer)
library(magrittr)
library(hrbrthemes)
library(extrafont)
library(gganimate)
library(transformr)
library(gt)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
library(tm)
Sys.setenv(SPOTIFY_CLIENT_ID = '1ebacb60ef2044ccadab18602f7c0b8f')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '6fb54464f8dc45c88387a4fadde775db')

access_token <- get_spotify_access_token()

# So it turns out that I am completely unable to get any data from Germany or
# the UK because I have a USA Spotify account. What I will do for this milestone
# is get the spotify top 200 tracks for the past 3 Februarys (Spotify only has
# data up until 2017) and store them in their own dataframe (UK and Germany).
# Since the dataframes do not give me details about the genre or any analysis,
# that means I'll have to do it individually for every song, which is a little
# absurd given the time for this project. My plan is to hopefully get Spotify to
# give me access to the global market, if not I will narrow my project.


```

# DATA TO BE ADDED

```{r ukcharts, echo=FALSE}
# I added this because I thought it would fix the problem with spotify returning
# NULL observations, but it did not :(

options(stringsAsFactors = FALSE)

# Thank you Mitchell for the lines of code below!!

uk2000_hits <- "http://www.uk-charts.top-source.info/top-100-2000.shtml" %>%
  read_html()

uk_2000_data <- html_nodes(uk2000_hits, "td") %>% 
  html_text()

# Okay so contrary to my belief, rep will not be the best way to split the list
# up, but the as.data.frame function will automatically continue to split the
# first three rows into a separate column. Perhaps there is another way to do
# this, but I like this method for now.

uk_2000_data <- as.data.frame(split(uk_2000_data, 1:3)) %>% 
  rename(position = X1,
         artist = X2,
         title = X3)

## Test out if Spotify will give me the genres of titles. This does not work at
## the moment, but I believe that once I figure this aspect out, it shall be
## easy to move onwards with the data-gathering.

# get_track_audio_features(uk_2000_data$title)

## Get tracks from 2001-2010 in UK

uk2001_hits <- "http://www.uk-charts.top-source.info/top-100-2001.shtml" %>%
  read_html()

uk2001_hits <- html_nodes(uk2001_hits, "td") %>%
  html_text()

uk2001_data <- as.data.frame(split(uk2001_hits, 1:3)) %>% 
  rename(position = X1,
         artist = X2,
         title = X3)

uk2002_hits <- "http://www.uk-charts.top-source.info/top-100-2002.shtml" %>%
  read_html()

uk2002_hits <- html_nodes(uk2002_hits, "td") %>%
  html_text()

uk2002_data <- as.data.frame(split(uk2002_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2003_hits <- "http://www.uk-charts.top-source.info/top-100-2003.shtml" %>%
  read_html()

uk2003_hits <- html_nodes(uk2003_hits, "td") %>%
  html_text()

uk2003_data <- as.data.frame(split(uk2003_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2004_hits <- "http://www.uk-charts.top-source.info/top-100-2004.shtml" %>%
  read_html()

uk2004_hits <- html_nodes(uk2004_hits, "td") %>%
  html_text()

uk2004_data <- as.data.frame(split(uk2004_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2005_hits <- "http://www.uk-charts.top-source.info/top-100-2005.shtml" %>%
  read_html()

uk2005_hits <- html_nodes(uk2005_hits, "td") %>%
  html_text()

uk2005_data <- as.data.frame(split(uk2005_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2006_hits <- "http://www.uk-charts.top-source.info/top-100-2006.shtml" %>%
  read_html()

uk2006_hits <- html_nodes(uk2006_hits, "td") %>%
  html_text()

uk2006_data <- as.data.frame(split(uk2006_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2007_hits <- "http://www.uk-charts.top-source.info/top-100-2007.shtml" %>%
  read_html()

uk2007_hits <- html_nodes(uk2007_hits, "td") %>%
  html_text()

uk2007_data <- as.data.frame(split(uk2007_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2008_hits <- "http://www.uk-charts.top-source.info/top-100-2008.shtml" %>%
  read_html()

uk2008_hits <- html_nodes(uk2008_hits, "td") %>%
  html_text()

uk2008_data <- as.data.frame(split(uk2008_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2009_hits <- "http://www.uk-charts.top-source.info/top-100-2009.shtml" %>%
  read_html()

uk2009_hits <- html_nodes(uk2009_hits, "td") %>%
  html_text()

uk2009_data <- as.data.frame(split(uk2009_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

uk2010_hits <- "http://www.uk-charts.top-source.info/top-100-2010.shtml" %>%
  read_html()

uk2010_hits <- html_nodes(uk2010_hits, "td") %>%
  html_text()

uk2010_data <- as.data.frame(split(uk2010_hits, 1:3)) %>%
  rename(position = X1,
         artist = X2,
         title = X3)

# Map function that iterates over every row in track.artists, getting the id and
# feeding it into the get_artist function

ger2000_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2000" %>%
  read_html()

ger2000_hits <- html_nodes(ger2000_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("\\n+", "")%>%
  trimws()%>%
  tibble()

colnames(ger2000_hits)<-c("Column")

ger2000_hits<- ger2000_hits %>% 
  mutate(Names=str_split(Column,"\\s{36}"))

ger2000_data <- data.frame(matrix(unlist(ger2000_hits$Names),
                                  nrow=100, byrow=T),stringsAsFactors=FALSE)

ger2001_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2001" %>%
  read_html()

ger2001_hits <- html_nodes(ger2001_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2001_hits)<-c("Column")

ger2001_hits <- ger2001_hits %>%
  mutate(Names=str_split(Column, "\\s{36}"))

ger2001_data <- data.frame(matrix(unlist(ger2001_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2002_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2002" %>%
  read_html()

ger2002_hits <- html_nodes(ger2002_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2002_hits)<-c("Column")

ger2002_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2002_data <- data.frame(matrix(unlist(ger2002_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2003_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2003" %>%
  read_html()

ger2003_hits <- html_nodes(ger2003_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2003_hits)<-c("Column")

ger2003_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2003_data <- data.frame(matrix(unlist(ger2003_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2004_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2004" %>%
  read_html()

ger2004_hits <- html_nodes(ger2004_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2004_hits)<-c("Column")

ger2004_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2004_data <- data.frame(matrix(unlist(ger2004_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2005_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2005" %>%
  read_html()

ger2005_hits <- html_nodes(ger2005_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2005_hits)<-c("Column")

ger2005_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2005_data <- data.frame(matrix(unlist(ger2005_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2006_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2006" %>%
  read_html()

ger2006_hits <- html_nodes(ger2006_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2006_hits)<-c("Column")

ger2006_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2006_data <- data.frame(matrix(unlist(ger2006_hits$Names),
                                  nrow=100,
                                  byrow = T),
                           stringsAsFactors = FALSE)

ger2007_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2007" %>%
  read_html()

ger2007_hits <- html_nodes(ger2007_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2007_hits)<-c("Column")

ger2007_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2007_data <- data.frame(matrix(unlist(ger2007_hits$Names),
                                  nrow=100,
                                  byrow = T), stringsAsFactors = FALSE)

ger2008_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2008" %>%
  read_html()

ger2008_hits <- html_nodes(ger2008_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2008_hits)<-c("Column")

ger2008_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2008_data <- data.frame(matrix(unlist(ger2008_hits$Names),
                                  nrow=100,
                                  byrow = T), stringsAsFactors = FALSE)

ger2009_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2009" %>%
  read_html()

ger2009_hits <- html_nodes(ger2009_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2009_hits)<-c("Column")

ger2009_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2009_data <- data.frame(matrix(unlist(ger2009_hits$Names),
                                  nrow=100,
                                  byrow = T), stringsAsFactors = FALSE)

ger2010_hits <- "https://www.offiziellecharts.de/charts/single-jahr/for-date-2010" %>%
  read_html()

ger2010_hits <- html_nodes(ger2010_hits, ".year-mode") %>%
  html_text() %>%
  str_replace_all("//n+", "") %>%
  trimws() %>%
  tibble()

colnames(ger2010_hits)<-c("Column")

ger2010_hits %<>% mutate(Names=str_split(Column, "\\s{36}"))

ger2010_data <- data.frame(matrix(unlist(ger2010_hits$Names),
                                  nrow=100,
                                  byrow = T), stringsAsFactors = FALSE)

# This will be something I would like to do with the 2000-2010 data. Here is a
# demo with the Spotify Top 200 playlist that I would want to replicate with my
# own data. The problem with my data currently is that the function that should
# be working isn't, and every spotify tutorial uses the same method as mine.
# Also, I do not have access to the Spotify UK/GER markets, so there are songs
# that I am missing from my top playlists. Most of the data I gathered will be
# in the playlists themselves, and I am still trying to figure out how to clean
# up the GER data so I can easily display it somewhere on the website.

# Here I will get the audio features for every year in both uk and germany.

uk_2000 <- get_playlist("7uQBCcnNuxOBv0jFbEcYjH")
uk2000_tracks <- get_playlist_tracks("7uQBCcnNuxOBv0jFbEcYjH") 
uk2000_features <- get_track_audio_features(uk2000_tracks$track.id)

uk_2001 <- get_playlist("28MXvLEP4jZ6c5kVIP8ke5")
uk2001_tracks <- get_playlist_tracks("28MXvLEP4jZ6c5kVIP8ke5")
uk2001_features <- get_track_audio_features(uk2001_tracks$track.id)

uk2002 <- get_playlist("7vQW2yhyPeUys745cjd4qW")
uk2002_tracks <- get_playlist_tracks("7vQW2yhyPeUys745cjd4qW")
uk2002_features <- get_track_audio_features(uk2002_tracks$track.id)

uk2003 <- get_playlist("7ajCdWcuELFirRcGl9LKsv")
uk2003_tracks <- get_playlist_tracks("7ajCdWcuELFirRcGl9LKsv")
uk2003_features <- get_track_audio_features(uk2003_tracks$track.id)

# Start here

uk2004 <- get_playlist("4d9CrfTDJ7WgDXL7xy4gnu")
uk2004_tracks <- get_playlist_tracks("4d9CrfTDJ7WgDXL7xy4gnu")
uk2004_features <- get_track_audio_features(uk2004_tracks$track.id)

uk2005 <- get_playlist("2luAWE5y4EjcF3eeecXqqL")
uk2005_tracks <- get_playlist_tracks("2luAWE5y4EjcF3eeecXqqL")
uk2005_features <- get_track_audio_features(uk2005_tracks$track.id)

uk2006 <- get_playlist("246jBtzSV8noLKfwPhxK9L")
uk2006_tracks <- get_playlist_tracks("246jBtzSV8noLKfwPhxK9L")
uk2006_features <- get_track_audio_features(uk2006_tracks$track.id)

uk2007 <- get_playlist("41tjYI2R4zuKCR6Jpkcurs")
uk2007_tracks <- get_playlist_tracks("41tjYI2R4zuKCR6Jpkcurs")
uk2007_features <- get_track_audio_features(uk2007_tracks$track.id)

uk2008 <- get_playlist("2e6HTZLlouOqvX2hFfrK7M")
uk2008_tracks <- get_playlist_tracks("2e6HTZLlouOqvX2hFfrK7M")
uk2008_features <- get_track_audio_features(uk2008_tracks$track.id)

uk2009 <- get_playlist("36Wp100hDpZ39S7rAkeW2B")
uk2009_tracks <- get_playlist_tracks("36Wp100hDpZ39S7rAkeW2B")
uk2009_features <- get_track_audio_features(uk2009_tracks$track.id)

uk2010 <- get_playlist("1oFHWJu7rH78TBCxbUvLne")
uk2010_tracks <- get_playlist_tracks("1oFHWJu7rH78TBCxbUvLne")
uk2010_features <- get_track_audio_features(uk2010_tracks$track.id)

ger2000 <- get_playlist("3mwXtmIDVIImnHEhF25aXk")
ger2000_tracks <- get_playlist_tracks("3mwXtmIDVIImnHEhF25aXk")
ger2000_features <- get_track_audio_features(ger2000_tracks$track.id)

ger2001 <- get_playlist("5Xl6JK20GTICxAQsMjrp93")
ger2001_tracks <- get_playlist_tracks("5Xl6JK20GTICxAQsMjrp93")
ger2001_features <- get_track_audio_features(ger2001_tracks$track.id)

ger2002 <- get_playlist("4pN5sDpaQn5pGVJQJ8Nm7j")
ger2002_tracks <- get_playlist_tracks("4pN5sDpaQn5pGVJQJ8Nm7j")
ger2002_features <- get_track_audio_features(ger2002_tracks$track.id)

ger2003 <- get_playlist("4CfPTjH2UOLZr3FjtbmnPB")
ger2003_tracks <- get_playlist_tracks("4CfPTjH2UOLZr3FjtbmnPB")
ger2003_features <- get_track_audio_features(ger2003_tracks$track.id)

ger2004 <- get_playlist("6RsriY4UcnhHpKNoeVYbu4")
ger2004_tracks <- get_playlist_tracks("6RsriY4UcnhHpKNoeVYbu4")
ger2004_features <- get_track_audio_features(ger2004_tracks$track.id)

ger2005 <- get_playlist("2nfm7TsAcuHr7p1MrOFKcw")
ger2005_tracks <- get_playlist_tracks("2nfm7TsAcuHr7p1MrOFKcw")
ger2005_features <- get_track_audio_features(ger2005_tracks$track.id)

ger2006 <- get_playlist("77N8qjXKrsVVMv8hI8jNxG")
ger2006_tracks <- get_playlist_tracks("77N8qjXKrsVVMv8hI8jNxG")
ger2006_features <- get_track_audio_features(ger2006_tracks$track.id)

ger2007 <- get_playlist("4mwHWiCKwzdIx3ANL19vRY")
ger2007_tracks <- get_playlist_tracks("4mwHWiCKwzdIx3ANL19vRY")
ger2007_features <- get_track_audio_features(ger2007_tracks$track.id)

ger2008 <- get_playlist("3o5sU5OWHsFsbh9FXjYQKE")
ger2008_tracks <- get_playlist_tracks("3o5sU5OWHsFsbh9FXjYQKE")
ger2008_features <- get_track_audio_features(ger2008_tracks$track.id)

ger2009 <- get_playlist("1teQpbhtQztADlDeANRwUs")
ger2009_tracks <- get_playlist_tracks("1teQpbhtQztADlDeANRwUs")
ger2009_features <- get_track_audio_features(ger2009_tracks$track.id)

ger2010 <- get_playlist("1RZV5fBYJUEfeYbT9kiDnk")
ger2010_tracks <- get_playlist_tracks("1RZV5fBYJUEfeYbT9kiDnk")
ger2010_features <- get_track_audio_features(ger2010_tracks$track.id)

# Here I store all the danceability, valence, and tempo features per year.

danceability_uk_2000 <- uk2000_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2000") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2000 <- uk2000_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2000") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2000 <- uk2000_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2000") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2000 <- uk2000_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2000") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2001 <- uk2001_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2001") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2001 <- uk2001_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2001") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2001 <- uk2001_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2001") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2001 <- uk2001_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2001") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2002 <- uk2002_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2002") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2002 <- uk2002_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2002") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2002 <- uk2002_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2002") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2002 <- uk2002_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2002") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2003 <- uk2003_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2003") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2003 <- uk2003_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2003") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2003 <- uk2003_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2003") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2003 <- uk2003_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2003") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2004 <- uk2004_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2004") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2004 <- uk2004_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2004") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2004 <- uk2004_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2004") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2004 <- uk2004_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2004") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2005 <- uk2005_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2005") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2005 <- uk2005_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2005") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2005 <- uk2005_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2005") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2005 <- uk2005_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2005") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2006 <- uk2006_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2006") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2006 <- uk2006_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2006") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2006 <- uk2006_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2006") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2006 <- uk2006_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2006") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2007 <- uk2007_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2007") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2007 <- uk2007_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2007") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2007 <- uk2007_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2007") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2007 <- uk2007_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2007") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2008 <- uk2008_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2008") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2008 <- uk2008_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2008") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2008 <- uk2008_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2008") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2008 <- uk2008_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2008") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2009 <- uk2009_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2009") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2009 <- uk2009_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2009") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2009 <- uk2009_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2009") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2009 <- uk2009_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2009") +
  theme_ipsum(base_family = "Calibri")

danceability_uk_2010 <- uk2010_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in UK Charts 2010") +
  theme_ipsum(base_family = "Calibri")

valence_uk_2010 <- uk2010_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in UK Charts 2010") +
  theme_ipsum(base_family = "Calibri") 

tempo_uk_2010 <- uk2010_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in UK Charts 2010") +
  theme_ipsum(base_family = "Calibri")

energy_uk_2010 <- uk2010_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in UK Charts 2010") +
  theme_ipsum(base_family = "Calibri")

# Here are the germany datas

danceability_ger_2000 <- ger2000_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2000") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2000 <- ger2000_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2000") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2000 <- ger2000_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2000") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2000 <- ger2000_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2000") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2001 <- ger2001_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2001") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2001 <- ger2001_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2001") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2001 <- ger2001_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2001") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2001 <- ger2001_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2001") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2002 <- ger2002_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2002") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2002 <- ger2002_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2002") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2002 <- ger2002_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2002") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2002 <- ger2002_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2002") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2003 <- ger2003_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2003") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2003 <- ger2003_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2003") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2003 <- ger2003_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2003") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2003 <- ger2003_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2003") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2004 <- ger2004_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2004") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2004 <- ger2004_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2004") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2004 <- ger2004_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2004") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2004 <- ger2004_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2004") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2005 <- ger2005_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2005") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2005 <- ger2005_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2005") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2005 <- ger2005_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2005") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2005 <- ger2005_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2005") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2006 <- ger2006_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2006") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2006 <- ger2006_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2006") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2006 <- ger2006_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2006") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2006 <- ger2006_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2006") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2007 <- ger2007_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2007") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2007 <- ger2007_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2007") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2007 <- ger2007_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2007") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2007 <- ger2007_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2007") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2008 <- ger2008_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2008") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2008 <- ger2008_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2008") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2008 <- ger2008_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2008") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2008 <- ger2008_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2008") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2009 <- ger2009_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2009") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2009 <- ger2009_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2009") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2009 <- ger2009_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2009") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2009 <- ger2009_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2009") +
  theme_ipsum(base_family = "Calibri")

danceability_ger_2010 <- ger2010_features %>%
  ggplot(aes(danceability)) +
  geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
  ggtitle("Danceability Distribution in Germany Charts 2010") +
  theme_ipsum(base_family = "Calibri")

valence_ger_2010 <- ger2010_features %>%
  ggplot(aes(valence)) +
  geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
  ggtitle("Valence Distribution in Germany Charts 2010") +
  theme_ipsum(base_family = "Calibri")

tempo_ger_2010 <- ger2010_features %>%
  ggplot(aes(tempo)) +
  geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
  ggtitle("Tempo Distribution in Germany Charts 2010") +
  theme_ipsum(base_family = "Calibri")

energy_ger_2010 <- ger2010_features %>%
  ggplot(aes(energy)) +
  geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
  ggtitle("Energy Distribution in Germany Charts 2010") +
  theme_ipsum(base_family = "Calibri")


# Testing for function


# What function should do: Get the genres from each song. Then, I would use a
# map function and paste the genres onto a new column in the uk2000_genre df.

get_genre <- function(df) {
  for(i in 1:nrow(df)) {
    SongID <- df$track.artist[[i]][[2]]
    SongGenre <- get_artist(SongID[1])
    df$genre[i] <- paste(unlist(SongGenre[["genres"]]),
                                  sep="", collapse=",")
  }
  df
}

uk2000_tracks = get_genre(uk2000_tracks)
uk2001_tracks %<>%
  get_genre()
uk2002_tracks %<>%
  get_genre()
uk2003_tracks %<>%
  get_genre()
uk2004_tracks %<>%
  get_genre()
uk2005_tracks %<>%
  get_genre()
uk2006_tracks %<>%
  get_genre()
uk2007_tracks %<>%
  get_genre()
uk2008_tracks %<>%
  get_genre()
uk2009_tracks %<>%
  get_genre()
uk2010_tracks %<>%
  get_genre()
ger2000_tracks %<>%
  get_genre()
ger2001_tracks %<>%
  get_genre()
ger2002_tracks %<>%
  get_genre()
ger2003_tracks %<>%
  get_genre()
ger2004_tracks %<>%
  get_genre()
ger2005_tracks %<>%
  get_genre()
ger2006_tracks %<>%
  get_genre()
ger2007_tracks %<>%
  get_genre()
ger2008_tracks %<>%
  get_genre()
ger2009_tracks %<>%
  get_genre()
ger2010_tracks %<>%
  get_genre()

# Cleaning up the UK data, creating a year and position variable so I can
# combine everything into one huge dataset.

uk2000_tracks %<>%
  mutate(year = 2000,
         position = 1:nrow(.))
uk2001_tracks %<>%
  mutate(year = 2001,
         position = 1:nrow(.))
uk2002_tracks %<>%
  mutate(year = 2002,
         position = 1:nrow(.))
uk2003_tracks %<>%
  mutate(year = 2003,
         position = 1:nrow(.))
uk2004_tracks %<>%
  mutate(year = 2004,
         position = 1:nrow(.))
uk2005_tracks %<>%
  mutate(year = 2005,
         position = 1:nrow(.))
uk2006_tracks %<>%
  mutate(year = 2006,
         position = 1:nrow(.))
uk2007_tracks %<>%
  mutate(year = 2007,
         position = 1:nrow(.))
uk2008_tracks %<>%
  mutate(year = 2008,
         position = 1:nrow(.))
uk2009_tracks %<>%
  mutate(year = 2009,
         position = 1:nrow(.))
uk2010_tracks %<>%
  mutate(year = 2010,
         position = 1:nrow(.))

ger2000_tracks %<>%
  mutate(year = 2000,
         position = 1:nrow(.))
ger2001_tracks %<>%
  mutate(year = 2001,
         position = 1:nrow(.))
ger2002_tracks %<>%
  mutate(year = 2002,
         position = 1:nrow(.))
ger2003_tracks %<>%
  mutate(year = 2003,
         position = 1:nrow(.))
ger2004_tracks %<>%
  mutate(year = 2004,
         position = 1:nrow(.))
ger2005_tracks %<>%
  mutate(year = 2005,
         position = 1:nrow(.))
ger2006_tracks %<>%
  mutate(year = 2006,
         position = 1:nrow(.))
ger2007_tracks %<>%
  mutate(year = 2007,
         position = 1:nrow(.))
ger2008_tracks %<>%
  mutate(year = 2008,
         position = 1:nrow(.))
ger2009_tracks %<>%
  mutate(year = 2009,
         position = 1:nrow(.))
ger2010_tracks %<>%
  mutate(year = 2010,
         position = 1:nrow(.))

# Here, I create the UK and Germany charts data so I can refer to this in the
# shiny app. This will allow me to look at the whole dataset and make decade
# comparisons :)

uk_charts <- rbind(uk2000_tracks,
                   uk2001_tracks,
                   uk2002_tracks,
                   uk2003_tracks,
                   uk2004_tracks,
                   uk2005_tracks,
                   uk2006_tracks,
                   uk2007_tracks,
                   uk2008_tracks,
                   uk2009_tracks,
                   uk2010_tracks)

ger_charts <- rbind(ger2000_tracks,
                    ger2001_tracks,
                    ger2002_tracks,
                    ger2003_tracks,
                    ger2004_tracks,
                    ger2005_tracks,
                    ger2006_tracks,
                    ger2007_tracks,
                    ger2008_tracks,
                    ger2009_tracks,
                    ger2010_tracks)

uk_features <- rbind(uk2000_features,
                     uk2001_features,
                     uk2002_features,
                     uk2003_features,
                     uk2004_features,
                     uk2005_features,
                     uk2006_features,
                     uk2007_features,
                     uk2008_features,
                     uk2009_features,
                     uk2010_features)

uk_charts <- cbind(uk_charts,
                   uk_features)

ger_features <- rbind(ger2000_features,
                      ger2001_features,
                      ger2002_features,
                      ger2003_features,
                      ger2004_features,
                      ger2005_features,
                      ger2006_features,
                      ger2007_features,
                      ger2008_features,
                      ger2009_features,
                      ger2010_features)

ger_charts <- cbind(ger_charts,
                    ger_features)

saveRDS(uk_charts, file = "uk_charts")
saveRDS(ger_charts, file = "ger_charts")

uk_charts_listing <- rbind(uk_2000_data,
                           uk2001_data,
                           uk2002_data,
                           uk2003_data,
                           uk2004_data,
                           uk2005_data,
                           uk2006_data,
                           uk2007_data,
                           uk2008_data,
                           uk2009_data,
                           uk2010_data)

ger_charts_listing <- rbind(ger2000_data,
                            ger2001_data,
                            ger2002_data,
                            ger2003_data,
                            ger2004_data,
                            ger2005_data,
                            ger2006_data,
                            ger2007_data,
                            ger2008_data,
                            ger2009_data,
                            ger2010_data)


# Testing how to make graphs for data...

uk_charts_listing %<>%
  mutate(year = rep(2000:2010, each = 100))

ger_charts_listing %<>%
  mutate(year = rep(2000:2010, each = 100)) %>%
  rename(artist = X1,
         title = X2)


# This function is directly taken from Stack Overflow. User got documentation
# from toupper and used that to write out this function (or perhaps it's from
# the data itself?):
# https://stackoverflow.com/questions/6364783/capitalize-the-first-letter-of-both-words-in-a-two-word-string

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}

yearly_uk_artists <- uk_charts_listing %>%
  count(tolower(artist)) %>%
  arrange(desc(n)) %>%
  rename(artist = `tolower(artist)`) %>%
  mutate(artist = sapply(artist, simpleCap)) %>%
  head(10)

yearly_uk_songs <- uk_charts_listing %>%
  group_by(artist) %>%
  count(tolower(title)) %>%
  arrange(desc(n)) %>%
  rename(title = `tolower(title)`) %>%
  mutate(title = sapply(title, simpleCap)) %>%
  head(10)

yearly_uk_genres <- data.frame(table(unlist(strsplit(tolower(uk_charts$genre), ",")))) %>%
  arrange(desc(Freq)) %>%
  head(25)

yearly_ger_artists <- ger_charts_listing %>%
  mutate(artist = tolower(artist)) %>%
  count(artist) %>%
  arrange(desc(n)) %>%
  mutate(artist = sapply(artist, simpleCap)) %>%
  head(10)
  
yearly_ger_songs <- ger_charts_listing %>%
  group_by(artist) %>%
  mutate(title = tolower(title)) %>%
  count(title) %>%
  arrange(desc(n)) %>%
  mutate(title = sapply(title, simpleCap)) %>%
  head(10)

yearly_ger_genres <- data.frame(table(unlist(strsplit(tolower(ger_charts$genre), ",")))) %>%
  arrange(desc(Freq)) %>%
  head(25)

foruk_artists <- yearly_uk_artists %>%
  gt() %>%
  tab_header(title = "Artists that have Appeared the Most in UK Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(artist = "Artist",
             n = "Count")

foruk_songs <- yearly_uk_songs %>%
  ungroup(artist) %>%
  gt() %>%
  tab_header(title = "Songs that have Appeared the Most in UK Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(artist = "Artist",
             title = "Song Title",
             n = "Count")

foruk_genres <- yearly_uk_genres %>%
  gt() %>%
  tab_header(title = "Most Popular Genres in UK Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(Var1 = "Genre",
             Freq = "Count") %>%
  tab_footnote("Most songs fall under multiple genres.",
               locations = cells_title(groups = "subtitle"))

forger_artists <- yearly_ger_artists %>%
  gt() %>%
  tab_header(title = "Artists that have Appeared the Most in German Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(artist = "Artist",
             n = "Count")

forger_songs <- yearly_ger_songs %>%
  ungroup(artist) %>%
  gt() %>%
  tab_header(title = "Songs that have Appeared the Most in German Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(artist = "Artist",
             title = "Song Title",
             n = "Count")

forger_genres <- yearly_ger_genres %>%
  gt() %>%
  tab_header(title = "Most Popular Genres in German Charts",
             subtitle = "Data from 2000 - 2010") %>%
  cols_label(Var1 = "Genre",
             Freq = "Count") %>%
  tab_footnote("Most songs fall under multiple genres.",
               locations = cells_title(groups = "subtitle"))




uk_danceability <- uk_charts %>%
                ggplot(aes(danceability)) +
                geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
                ggtitle("Danceability Distribution in UK Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

uk_valence <- uk_charts %>%
                ggplot(aes(valence)) +
                geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
                ggtitle("Valence Distribution in UK Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

uk_tempo <- uk_charts %>%
                ggplot(aes(tempo)) +
                geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
                transition_time(year) +
                labs(title = "Tempo Distribution in UK Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

uk_energy <- uk_charts %>%
                ggplot(aes(energy)) +
                geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
                ggtitle("Energy Distribution in UK Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

ger_danceability <- ger_charts %>%
                ggplot(aes(danceability)) +
                geom_density(fill = "#faac0f", colour = "#fcab08", alpha = 0.7) +
                ggtitle("Danceability Distribution in Germany Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

ger_valence <- ger_charts %>%
                ggplot(aes(valence)) +
                geom_density(fill = "#69b3a2", colour = "#e9ecef", alpha = 0.7) +
                ggtitle("Valence Distribution in Germany Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

ger_tempo <- ger_charts %>%
                ggplot(aes(tempo)) +
                geom_density(fill = "#4287f5", colour = "#316fd4", alpha = 0.7) +
                transition_time(year) +
                labs(title = "Tempo Distribution in Germany Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

ger_energy <- ger_charts %>%
                ggplot(aes(energy)) +
                geom_density(fill = "#f2493d", colour = "#f090e9", alpha = 0.7) +
                ggtitle("Energy Distribution in Germany Charts {closest_state}") +
                theme_ipsum(base_family = "Calibri") +
                transition_states(year)

```

```{r word_cloud_maker, echo=FALSE}

ukcloud <- uk_charts %>%
  separate_rows(genre, sep = ',') %>%
  group_by(genre = tolower(genre), year) %>%
  filter(!genre == "") %>%
  summarise(Count = n()) %>%
  ungroup(genre) %>%
  arrange(year)

gercloud <- ger_charts %>%
  separate_rows(genre, sep = ',') %>%
  group_by(genre = tolower(genre), year) %>%
  filter(!genre == "") %>%
  summarise(Count = n()) %>%
  ungroup(genre) %>%
  arrange(year)



```


```{r set_wd, echo=FALSE}

setwd("C:/Users/Saul/Documents/milestone4/UK_GER_Charts/")

saveRDS(ukcloud, "ukcloud.rds")
saveRDS(gercloud, "gercloud.rds")

anim_save("uk_danceability.gif", animate(uk_danceability))
anim_save("uk_valence.gif", animate(uk_valence))
anim_save("uk_tempo.gif", animate(uk_tempo))
anim_save("uk_energy.gif", animate(uk_energy))
anim_save("ger_danceability.gif", animate(ger_danceability))
anim_save("ger_valence.gif", animate(ger_valence))
anim_save("ger_tempo.gif", animate(ger_tempo))
anim_save("ger_energy.gif", animate(ger_energy))


saveRDS(uk_charts, file = "uk_charts.rds")
saveRDS(ger_charts, file = "ger_charts.rds")
```



